config/routes.rb
Rails.application.routes.draw do
  root to: 'media_items#index'

  resources :media_items, path: :media do
    member do
      post '/complete', action: :complete
      post :snooze
    end

    collection do
      put '/bulk_change_queue', action: :bulk_change_queue
      put '/bulk_mark_completed', action: :bulk_mark_completed
      delete '/bulk_destroy', action: :bulk_destroy
    end

    resources :media_notes, as: :notes,
                            path: :notes,
                            only: %i[create update destroy],
                            shallow: true
  end

  resources :media_queues, as: :queues, path: 'queues', only: %i[new edit create update destroy]

  resource :user_profile, only: %i[show update]
  resources :media_priorities, only: %i[index create]
  resources :integrations, only: %i[index new] do
    collection do
      get :authentication_redirect
      post :synchronize
    end
  end
end

app/models/media_queue.rb
class MediaQueue < ApplicationRecord
  belongs_to :user

  has_many :media_items, dependent: :nullify
  has_many :active_media_items,
    -> { merge(MediaItem.not_completed.not_snoozed) },
    class_name: 'MediaItem',
    dependent: :nullify

  validates :name, presence: true
  validates :color, presence: true

  def inbox?
    name == 'Inbox'
  end

  def update_active_media_items_count!
    update! active_media_items_count: active_media_items.count
  end
end

app/controllers/media_queues_controller.rb
class MediaQueuesController < ApplicationController
  def new
    @queue = MediaQueue.new
  end

  def edit
    @queue = current_user.queues.find(params[:id])
  end

  def create
    @queue = current_user.queues.build(queue_params)

    if @queue.save
      redirect_to media_items_path(queue: @queue), notice: 'Queue was successfully created.'
    else
      flash[:error] = 'There was an error creating the queue'
      render :new
    end
  end

  def update
    @queue = current_user.queues.find(params[:id])

    if @queue.update(queue_params)
      redirect_to media_items_path(queue: @queue), notice: 'Queue was successfully updated.'
    else
      flash[:error] = 'There was an error creating the queue'
      render :edit
    end
  end

  def destroy
    @queue = current_user.queues.find(params[:id])
    @queue.destroy

    redirect_to media_items_path, notice: 'Queue was successfully destroyed.'
  end

  private

  def queue_params
    params.require(:media_queue).permit(:name, :color)
  end
end

app/views/media_queues/_edit.html.erb
<h2 class="page-header">Edit Queue</h2>

<%= render 'form', queue: queue, url: queue_path(queue), method: :patch %>

app/views/media_queues/_form.html.erb
<%= form_with(model: queue, url: url, method: method, local: true) do |form| %>
  <% if queue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(queue.errors.count, "error") %> prohibited this queue from being saved:</h2>

      <ul>
        <% queue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name, placeholder: 'Name' %>

  <%= form.label :color %>
  <%= form.color_field :color %>

  <div class="mt-4">
    <%= form.submit class: 'primary button' %>
  </div>
<% end %>

app/views/media_queues/_new.html.erb
<h2 class="page-header">New Queue</h2>

<%= render 'form', queue: queue, url: queues_path(queue), method: :post %>

app/views/media_queues/edit.html.erb
<%= render 'media_queues/edit', queue: @queue %>

app/views/media_queues/edit.turbo_stream.erb
<%= turbo_stream.replace 'media-item-pane' do %>
  <%= render 'media_queues/edit', queue: @queue %>
<% end %>

app/views/media_queues/new.html.erb
<%= render 'media_queues/new', queue: @queue %>

app/views/media_queues/new.turbo_stream.erb
<%= turbo_stream.replace 'media-item-pane' do %>
  <%= render 'media_queues/new', queue: @queue %>
<% end %>