config/routes.rb
Rails.application.routes.draw do
  root to: 'media_items#index'

  resources :media_items, path: :media do
    member do
      post '/complete', action: :complete
      post :snooze
    end

    collection do
      put '/bulk_change_queue', action: :bulk_change_queue
      put '/bulk_mark_completed', action: :bulk_mark_completed
      delete '/bulk_destroy', action: :bulk_destroy
    end

    resources :media_notes, as: :notes,
                            path: :notes,
                            only: %i[create update destroy],
                            shallow: true
  end

  resources :media_queues, as: :queues, path: 'queues', only: %i[new edit create update destroy]

  resource :user_profile, only: %i[show update]
  resources :media_priorities, only: %i[index create]
  resources :integrations, only: %i[index new] do
    collection do
      get :authentication_redirect
      post :synchronize
    end
  end
end

app/views/layouts/shared/_head.html.erb
<title>MCQ</title>
<%= favicon_link_tag 'favicon.png' %>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<%= stylesheet_link_tag 'application', media: 'all' %>

<%= stylesheet_pack_tag 'bootstrap' %>
<%= javascript_pack_tag 'bootstrap' %>

<%= stylesheet_pack_tag 'application' %>
<%= javascript_pack_tag 'application', defer: 'defer' %>

app/views/layouts/shared/_header.html.erb
<nav class="md:hidden p-4 bg-white border-b-2" data-controller="mobile-navbar">
  <div class="flex items-center justify-between">
    <div class="flex items-center">
      <button class="block mr-4">
        <i class="bi bi-list icon" data-action="click->mobile-navbar#toggleNavigation"></i>
      </button>
      <%= current_user.email %>
    </div>
    <div class="flex items-center">
      <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'ml-4' %>
    </div>
  </div>

  <ul class="navigation hidden"
      data-target="mobile-navbar.navigation">
    <%= render 'layouts/shared/navigation_items' %>
  </ul>
</nav>

app/views/layouts/shared/_navigation_items.html.erb
<li>
  <%= active_link_to media_items_path, class: 'navigation-item' do %>
    <div class="small media-item">
      <i class="bi bi-play-circle icon"></i>
      All Media
    </div>
  <% end %>
</li>
<li>
  <%= active_link_to user_profile_path, class: 'navigation-item' do %>
    <div class="small media-item">
      <i class="bi bi-gear icon"></i>
      Settings
    </div>
  <% end %>
</li>
<li>
  <div class="py-4 px-2 rounded overflow-y-auto" style="max-height: 200px;">
    <div class="flex items-center mb-4">
      <div class="text-gray-600 uppercase text-sm flex-grow">My Queues</div>
      <%= turbo_link_to new_queue_url,
                  class: 'text-gray-600 hover:text-gray-800',
                  data: {
                    tippy_content: 'New Queue',
                    testid: 'new-queue-btn'
                  } do %>
        <i class="bi bi-plus-circle icon"></i>
      <% end %>
    </div>
    <ul>
      <% current_user_queues.each do |queue| %>
        <li class="flex items-center" style="border-left: 3px solid <%= queue.color %>">
          <%= active_link_to queue.name,
                             media_items_path(queue: queue),
                             class: 'navigation-item sub-link',
                             active_extra: params[:queue].to_i == queue.id %>
          <span class="<%= params[:queue].to_i == queue.id ? '' : 'opacity-50' %> text-sm">
            <%= queue.active_media_items_count %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</li>

app/views/layouts/shared/_sidebar.html.erb
<div class="hidden md:flex flex-col justify-between fixed pin-t pin-b h-full
            border-r shadow-inner bg-white w-2/12" style="min-width: 200px;">
  <div>
    <div class="text-center pt-4">
      <h1 class="text-2xl flex justify-center">
        <%= link_to root_path, class: 'text-black hover:text-black' do %>
          <%= image_tag 'icon.png', width: 80, alt: 'MCQ Icon' %>
        <% end %>
      </h1>
      <span class="text-muted"><%= current_user.email %></span>

      <%= turbo_link_to 'Add Media', new_media_item_path, class: 'primary button inline-block w-3/4 mt-4' %>
    </div>

    <div class="p-4 mt-6">
      <ul class="navigation">
        <%= render 'layouts/shared/navigation_items' %>
      </ul>
    </div>
  </div>

  <div class="text-center pb-4">
    <%= link_to 'Sign out', sign_out_path, method: :delete %>
  </div>
</div>