config/routes.rb
Rails.application.routes.draw do
  root to: 'media_items#index'

  resources :media_items, path: :media do
    member do
      post '/complete', action: :complete
      post :snooze
    end

    collection do
      put '/bulk_change_queue', action: :bulk_change_queue
      put '/bulk_mark_completed', action: :bulk_mark_completed
      delete '/bulk_destroy', action: :bulk_destroy
    end

    resources :media_notes, as: :notes,
                            path: :notes,
                            only: %i[create update destroy],
                            shallow: true
  end

  resources :media_queues, as: :queues, path: 'queues', only: %i[new edit create update destroy]

  resource :user_profile, only: %i[show update]
  resources :media_priorities, only: %i[index create]
  resources :integrations, only: %i[index new] do
    collection do
      get :authentication_redirect
      post :synchronize
    end
  end
end

app/models/media_item.rb
require 'open-uri'

class MediaItem < ApplicationRecord
  include Loggable
  include Snoozeable

  MEDIA_TYPES = %i[
    Article
    Video
  ].freeze

  enum consumption_difficulty: {
    easy:   'easy',
    medium: 'medium',
    hard:   'hard'
  }

  belongs_to :user
  belongs_to :queue, class_name: 'MediaQueue', foreign_key: :media_queue_id
  belongs_to :priority,
             class_name: 'MediaPriority',
             foreign_key: :media_priority_id,
             optional: true

  has_many :notes, -> { order(:id) }, class_name: 'MediaNote', dependent: :destroy

  validates :url, presence: true

  after_create :log_creation!
  after_commit :retrieve_metadata_later, on: :create

  after_save :update_queue_counter_cache
  after_destroy :update_queue_counter_cache

  scope :completed, -> { where(complete: true) }
  scope :not_completed, -> { where(complete: false) }

  def title_or_url
    title.presence || url
  end

  def mark_complete
    return false if complete?

    with_log(:mark_complete) do
      update complete: true
    end
  end

  def estimated_consumption_time
    return super unless self[:estimated_consumption_time].present?

    (self[:estimated_consumption_time] / 60.0).ceil
  end

  def assign_estimated_consumption_difficulty
    return unless estimated_consumption_time.present?
    return if consumption_difficulty.present?

    difficulties = self.class.consumption_difficulties.keys
    self.consumption_difficulty =
      case
      when estimated_consumption_time <= 5 then difficulties[0]
      when estimated_consumption_time <= 20 then difficulties[1]
      else difficulties[2]
      end
  end

  def method_missing(method, *args)
    super unless type.present?
    super unless MEDIA_TYPES.map { |type| :"#{type.downcase}?" }.include?(method)

    :"#{self.type.downcase}?" == method
  end

  def assign_metadata_from_source(metadata_class: MediaItem::Metadata)
    metadata = metadata_class.from_url(url, media_item: self)
    return if metadata.blank?

    assign_attributes metadata.to_media_item_attributes
    self.title = title.presence || metadata.title
  end

  private

  def log_creation!
    activity_logs.create action: :create
  end

  def snoozeable?
    !complete?
  end

  def update_queue_counter_cache
    queue_changes = saved_changes[:media_queue_id]

    if queue_changes.present? && queue_changes.first.present?
      old_queue = MediaQueue.find queue_changes.first
      old_queue.update_active_media_items_count!
    end

    queue.update_active_media_items_count!
  end

  def retrieve_metadata_later
    MediaItem::RetrieveMetadataJob.perform_later id
  end
end

app/models/media_item/metadata.rb
class MediaItem::Metadata
  def initialize(service_id:, service_name:, media_item:)
    @service_id   = service_id
    @service_name = service_name
    @media_item   = media_item
  end

  class << self
    def from_url(url, media_item:)
      case
      when service_id = ::YouTube.extract_video_id_from_url(url)
        new service_id: service_id, service_name: 'YouTube', media_item: media_item
      else
        new service_id: nil, service_name: nil, media_item: media_item
      end
    end
  end

  def to_media_item_attributes
    {
      service_type:               service_name,
      service_id:                 service_id,
      estimated_consumption_time: consumption_time,
    }
  end

  private

  attr_reader :service_name,
              :service_id,
              :media_item

  delegate :title,
           :consumption_time,
           to: :service_metadata_client

  SERVICE_METADATA_CLIENTS = {
    'YouTube' => ::MediaItem::Metadata::YouTube,
    'Article' => ::MediaItem::Metadata::WebArticle,
  }.freeze

  def service_metadata_client
    return @service_metadata_client if @service_metadata_client.present?

    client = SERVICE_METADATA_CLIENTS.fetch(service_name, MediaItem::Metadata::WebArticle)
    @service_metadata_client = client.new(service_id, media_item: media_item)
  end
end

app/models/media_item/metadata/base_metadata.rb
class MediaItem::Metadata::BaseMetadata
  def initialize(service_id, media_item:)
    @service_id = service_id
    @media_item = media_item
  end

  private

  attr_reader :service_id,
              :media_item
end

app/models/media_item/metadata/web_article.rb
class MediaItem::Metadata::WebArticle < MediaItem::Metadata::BaseMetadata
  def title
    web_document.title
  end

  def consumption_time
    estimated_minutes_to_read.seconds
  end

  private

  WORDS_PER_MINUTE = 200.0

  def estimated_minutes_to_read
    (words_in_web_document.size / WORDS_PER_MINUTE).ceil.minutes
  end

  def words_in_web_document
    @web_document_content ||= web_document.content.squish.split(' ')
  end

  def web_document
    return @web_document if @web_document.present?

    raw_content = URI.open(media_item.url).read
    @web_document = Readability::Document.new(raw_content, tags: [], remove_empty_nodes: true)
  end
end

app/models/media_item/metadata/you_tube.rb
class MediaItem::Metadata::YouTube < MediaItem::Metadata::BaseMetadata
  def title
    youtube_video[:title]
  end

  def consumption_time
    youtube_video[:duration]
  end

  private

  def youtube_video
    return @youtube_video if @youtube_video.present?

    youtube_client = YouTube::Client.new
    @youtube_video = youtube_client.video(service_id)
  end
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_action :set_media_items_presenter, only: %i[index show]

  def index
  end

  def show
    @media_item = current_user.media_items.includes(:notes).find(params[:id])

    respond_to do |format|
      format.turbo_stream
      format.html { render :index }
    end
  end

  def new
    @media_item = current_user.media_items.new
  end

  def create
    @media_item = current_user.media_items.build(media_item_params)

    if @media_item.save
      redirect_to media_item_path(@media_item), notice: 'Added the media.'
    else
      flash[:error] = 'There was an error adding the media.'
      render :new
    end
  end

  def edit
    @media_item = current_user.media_items.find(params[:id])
  end

  def update
    @media_item = current_user.media_items.find(params[:id])

    if @media_item.update(media_item_params)
      redirect_to media_item_path(@media_item), notice: 'Updated the media.'
    else
      flash[:error] = 'There was an error editing the media.'
      render :edit
    end
  end

  def destroy
    @media_item = current_user.media_items.find(params[:id])

    if @media_item.destroy
      redirect_to_media_list notice: "Media '#{@media_item.title_or_url}' deleted."
    end
  end

  def complete
    @media_item = current_user.media_items.find(params[:id])

    if @media_item.mark_complete
      redirect_to media_item_path(@media_item), notice: 'Marked media as completed.'
    else
      flash[:error] = 'There was an error marking the media as completed.'
      render :show
    end
  end

  def snooze
    @media_item = current_user.media_items.find(params[:id])

    snooze_until = params[:snooze_until]
    snooze_until = Time.zone.parse(snooze_until) if snooze_until.present?
    if @media_item.snooze(until_time: snooze_until)
      notice =
        if snooze_until.nil?
          'Media item was unsnoozed.'
        else
          "Snoozed until #{@media_item.snooze_until}"
        end
      redirect_to_media_list notice: notice
    else
      flash[:error] = 'There was an error snoozing the media.'
      render :show
    end
  end

  def bulk_change_queue
    queue = current_user.queues.find(params[:queue_id])
    updated_items = current_user.media_items.where(id: bulk_ids).update media_queue_id: queue.id

    flash[:notice] = "Moved #{updated_items.length} media items to '#{queue.name}'."
    redirect_ajax_to media_items_url
  end

  def bulk_mark_completed
    media_items = current_user.media_items.not_completed.where(id: bulk_ids)
    ActiveRecord::Base.transaction do
      media_items.each { |media_item| media_item.mark_complete }
    end

    flash[:notice] = "Marked #{media_items.size} media items as completed."
    redirect_ajax_to media_items_url
  end

  def bulk_destroy
    destroyed_items = current_user.media_items.where(id: bulk_ids).destroy_all

    flash[:notice] = "Deleted #{destroyed_items.size} media items."
    redirect_ajax_to media_items_url
  end

  private

  def media_item_params
    params.require(:media_item).permit(
      :url,
      :title,
      :media_queue_id,
      :media_priority_id,
      :consumption_difficulty,
      :type,
    )
  end

  def bulk_ids
    params[:ids].split(',')
  end

  def current_queue
    return unless params[:queue].present?

    @current_queue ||= current_user.queues.find(params[:queue])
  end

  def media_items_collection
    base_association = current_user
    base_association = current_queue if current_queue.present?

    base_association.media_items.includes(:queue, :priority)
  end

  def set_media_items_presenter
    @presenter =
      MediaItemsPresenter.new(
        current_user,
        media_items_collection,
        params: params,
        queue: current_queue
      )
  end
end

app/helpers/media_item_helper.rb
module MediaItemHelper
  def consumption_difficulty_classes(difficulty)
    case difficulty
    when 'easy'   then 'text-green-600'
    when 'medium' then 'text-yellow-600'
    when 'hard'   then 'text-red-600'
    else ''
    end
  end

  def toggle_class_for_type(media_item, type)
    return 'toggled' if media_item.new_record? && type == 'Article'
    return 'toggled' if media_item.type == type

    ''
  end

  def media_icon(media_item)
    case media_item.type
    when 'Article' then 'bi bi-file-text'
    when 'Video' then 'bi bi-film'
    end
  end

  def state_select_options
    [
      ['Incomplete', :not_complete],
      ['Complete', :complete],
      ['Snoozed', :snoozed],
    ]
  end

  def snooze_until_options
    now = Time.zone.today

    [
      ['Until', 'Tomorrow',   now + 1.day],
      ['Until', 'Next week',  now + 1.week],
      ['For',   'Two weeks',  now + 2.weeks],
      ['Until', 'Next month', now + 1.month],
      ['For',   'Two months', now + 2.months],
    ]
  end

  def snooze_until_menu_item(media_item, snooze_until:, prefix: nil, label:)
    snooze_url = snooze_media_item_url(media_item, snooze_until: snooze_until, queue: params[:queue])
    content_tag(:li) do
      testid = ['snooze', prefix, label].compact.map(&:downcase).join('-')
      link_to(snooze_url, class: 'menu-item', method: :post, data: { testid: testid }) do
        snooze_until_label(prefix, label) +
        content_tag(:span, class: 'text-muted ml-4') do
          if snooze_until
            "#{snooze_until.to_date} at 9 AM"
          else
            'Now'
          end
        end
      end
    end
  end

  def snooze_until_label(prefix = nil, label)
    content_tag(:span) do
      if prefix
        content_tag(:span, class: 'opacity-75 mr-1') do
          prefix
        end
      else
        ''.html_safe
      end +
      content_tag(:span, class: 'font-medium') do
        label
      end
    end
  end
end

app/views/media_items/list_pane/_bulk_actions.html.erb
<div class="select-wrapper">
  <select class="w-auto mb-0"
          data-target="bulk-actions.action"
          data-action="change->bulk-actions#trigger"
          data-url="<%= bulk_change_queue_media_items_path %>"
          data-value-param-name="queue_id">
    <option value="null">Select a queue</option>
    <% queues.each do |queue| %>
      <option value="<%= queue.id %>"><%= queue.name %></option>
    <% end %>
  </select>
</div>

<button type="button"
        class="button"
        data-target="bulk-actions.action"
        data-action="click->bulk-actions#trigger"
        data-url="<%= bulk_mark_completed_media_items_path %>">
  Mark Completed
</button>

<button type="button"
        class="button"
        data-target="bulk-actions.action"
        data-action="click->bulk-actions#trigger"
        data-url="<%= bulk_destroy_media_items_path %>"
        data-method="delete"
        data-confirm-action="Are you sure?">
  Delete
</button>

app/views/media_items/list_pane/_filter.html.erb
<span data-controller="tooltip filter"
      data-tooltip-align="left"
      data-filter-default-label-value="<%= default_label %>">
  <input type="hidden"
         name="<%= filter_param %>"
         data-target="filter.hidden"
         value="<%= params[filter_param] %>" />

  <button type="button" class="text button" data-action="tooltip#toggle">
    <span data-target="filter.text">
      <% filter_value = filter_values.find { |value| value.second.to_s == params[filter_param] } %>
      <%= filter_value.try(:first).try(:capitalize) || default_label %>
    </span>
    <i class="bi bi-chevron-down icon ml-2 text-sm"></i>
  </button>

  <template data-target="tooltip.template">
    <ul class="menu">
      <% if show_none %>
        <li>
          <%= button_tag class: 'menu-item',
                         data: { 'filter-value' => '', 'action' => 'filter#select' } do %>
            None
          <% end %>
        </li>
      <% end %>
      <% filter_values.each do |label, value| %>
        <li>
          <%= button_tag class: 'menu-item',
                         data: {
                           'filter-value' => value,
                           'filter-label' => label,
                           'action' => 'filter#select',
                           'target' => 'filter.option',
                         } do %>
            <%= label.capitalize %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </template>
</span>

app/views/media_items/list_pane/_filters.html.erb
<%= form_with url: search_path,
              local: true,
              method: :get,
              class: 'mt-6 mb-4' do |f| %>

  <%= hidden_field_tag :queue, params[:queue] %>

  <%= f.text_field :search,
                   placeholder: 'Search...',
                   value: params[:search],
                   autocomplete: :off,
                   style: 'margin-bottom: 0;' %>

  <div class="toolbar">
    <%= render 'media_items/list_pane/filter',
               default_label: 'Difficulty',
               filter_param: :difficulty,
               filter_values: MediaItem.consumption_difficulties,
               show_none: true %>

    <%= render 'media_items/list_pane/filter',
               default_label: 'Priority',
               filter_param: :priority,
               filter_values: priorities,
               show_none: true %>

    <%= render 'media_items/list_pane/filter',
               default_label: 'Type',
               filter_param: :type,
               filter_values: MediaItem::MEDIA_TYPES.zip(MediaItem::MEDIA_TYPES),
               show_none: true %>

    <%= render 'media_items/list_pane/filter',
               default_label: 'Incomplete',
               filter_param: :state,
               filter_values: state_select_options,
               show_none: false %>

    <%= f.submit 'Filter', class: 'button primary' %>
  </div>
<% end %>

app/views/media_items/list_pane/_media_item.erb
<div class="border-b p-2 selected-indicator">
  <div class="row mb-0">
    <div class="column md11 text-lg pl-0">
      <div class="small media-item icon-top">
        <i class="<%= media_icon(media_item) %> icon text-muted"></i>
        <div class="media-text">
          <%= turbo_link_to truncate(media_item.title_or_url, length: 50),
                            presenter.path_for_media_item(media_item),
                            data: {
                              tooltip: media_item.title_or_url,
                              action: 'click->detail-pane#displayLoading',
                              target: 'detail-pane.selector'
                            } %>

          <div class="compact toolbar text-muted mb-0">
            <div class="small media-item">
              <i class="b bi-inbox icon"></i>
              <%= media_item.queue.name %>
            </div>
            <% if media_item.priority %>
              <div class="small media-item">
                <i class="b bi-flag icon"></i>
                <%= media_item.priority.title.capitalize %>
              </div>
            <% end %>
            <% if media_item.consumption_difficulty %>
              <div class="small media-item">
                <i class="bi bi-sliders icon"></i>
                <div class="<%= consumption_difficulty_classes(media_item.consumption_difficulty) %>">
                  <%= media_item.consumption_difficulty.capitalize %>
                </div>
              </div>
            <% end %>
            <% if media_item.estimated_consumption_time %>
              <div class="small media-item">
                <i class="bi bi-watch icon"></i>
                <%= pluralize media_item.estimated_consumption_time, 'minute' %>
              </div>
            <% end %>
            <% if media_item.snoozed? %>
              <div class="small media-item"
                    data-tippy-content="Snoozed until <%= media_item.formatted_snooze_until %>">
                <i class="bi bi-clock icon"></i>
                <%= media_item.formatted_snooze_until with_time: false %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="column md1 text-right">
      <%= check_box_tag :select_media_item,
                        media_item.id,
                        false,
                        class: 'mr-1',
                        data: {
                          target: 'bulk-actions.item',
                          action: 'change->bulk-actions#itemChanged'
                        } %>
      <%= external_link_to '', media_item.url, class: 'text-muted' %>
    </div>
  </div>
</div>