config/routes.rb
Rails.application.routes.draw do
  root to: 'media_items#index'

  resources :media_items, path: :media do
    member do
      post '/complete', action: :complete
      post :snooze
    end

    collection do
      put '/bulk_change_queue', action: :bulk_change_queue
      put '/bulk_mark_completed', action: :bulk_mark_completed
      delete '/bulk_destroy', action: :bulk_destroy
    end

    resources :media_notes, as: :notes,
                            path: :notes,
                            only: %i[create update destroy],
                            shallow: true
  end

  resources :media_queues, as: :queues, path: 'queues', only: %i[new edit create update destroy]

  resource :user_profile, only: %i[show update]
  resources :media_priorities, only: %i[index create]
  resources :integrations, only: %i[index new] do
    collection do
      get :authentication_redirect
      post :synchronize
    end
  end
end

app/models/media_item.rb
require 'open-uri'

class MediaItem < ApplicationRecord
  include Loggable
  include Snoozeable

  MEDIA_TYPES = %i[
    Article
    Video
  ].freeze

  enum consumption_difficulty: {
    easy:   'easy',
    medium: 'medium',
    hard:   'hard'
  }

  belongs_to :user
  belongs_to :queue, class_name: 'MediaQueue', foreign_key: :media_queue_id
  belongs_to :priority,
             class_name: 'MediaPriority',
             foreign_key: :media_priority_id,
             optional: true

  has_many :notes, -> { order(:id) }, class_name: 'MediaNote', dependent: :destroy

  validates :url, presence: true

  after_create :log_creation!
  after_commit :retrieve_metadata_later, on: :create

  after_save :update_queue_counter_cache
  after_destroy :update_queue_counter_cache

  scope :completed, -> { where(complete: true) }
  scope :not_completed, -> { where(complete: false) }

  def title_or_url
    title.presence || url
  end

  def mark_complete
    return false if complete?

    with_log(:mark_complete) do
      update complete: true
    end
  end

  def estimated_consumption_time
    return super unless self[:estimated_consumption_time].present?

    (self[:estimated_consumption_time] / 60.0).ceil
  end

  def assign_estimated_consumption_difficulty
    return unless estimated_consumption_time.present?
    return if consumption_difficulty.present?

    difficulties = self.class.consumption_difficulties.keys
    self.consumption_difficulty =
      case
      when estimated_consumption_time <= 5 then difficulties[0]
      when estimated_consumption_time <= 20 then difficulties[1]
      else difficulties[2]
      end
  end

  def method_missing(method, *args)
    super unless type.present?
    super unless MEDIA_TYPES.map { |type| :"#{type.downcase}?" }.include?(method)

    :"#{self.type.downcase}?" == method
  end

  def assign_metadata_from_source(metadata_class: MediaItem::Metadata)
    metadata = metadata_class.from_url(url, media_item: self)
    return if metadata.blank?

    assign_attributes metadata.to_media_item_attributes
    self.title = title.presence || metadata.title
  end

  private

  def log_creation!
    activity_logs.create action: :create
  end

  def snoozeable?
    !complete?
  end

  def update_queue_counter_cache
    queue_changes = saved_changes[:media_queue_id]

    if queue_changes.present? && queue_changes.first.present?
      old_queue = MediaQueue.find queue_changes.first
      old_queue.update_active_media_items_count!
    end

    queue.update_active_media_items_count!
  end

  def retrieve_metadata_later
    MediaItem::RetrieveMetadataJob.perform_later id
  end
end

app/models/media_item/metadata.rb
class MediaItem::Metadata
  def initialize(service_id:, service_name:, media_item:)
    @service_id   = service_id
    @service_name = service_name
    @media_item   = media_item
  end

  class << self
    def from_url(url, media_item:)
      case
      when service_id = ::YouTube.extract_video_id_from_url(url)
        new service_id: service_id, service_name: 'YouTube', media_item: media_item
      else
        new service_id: nil, service_name: nil, media_item: media_item
      end
    end
  end

  def to_media_item_attributes
    {
      service_type:               service_name,
      service_id:                 service_id,
      estimated_consumption_time: consumption_time,
    }
  end

  private

  attr_reader :service_name,
              :service_id,
              :media_item

  delegate :title,
           :consumption_time,
           to: :service_metadata_client

  SERVICE_METADATA_CLIENTS = {
    'YouTube' => ::MediaItem::Metadata::YouTube,
    'Article' => ::MediaItem::Metadata::WebArticle,
  }.freeze

  def service_metadata_client
    return @service_metadata_client if @service_metadata_client.present?

    client = SERVICE_METADATA_CLIENTS.fetch(service_name, MediaItem::Metadata::WebArticle)
    @service_metadata_client = client.new(service_id, media_item: media_item)
  end
end

app/models/media_item/metadata/base_metadata.rb
class MediaItem::Metadata::BaseMetadata
  def initialize(service_id, media_item:)
    @service_id = service_id
    @media_item = media_item
  end

  private

  attr_reader :service_id,
              :media_item
end

app/models/media_item/metadata/web_article.rb
class MediaItem::Metadata::WebArticle < MediaItem::Metadata::BaseMetadata
  def title
    web_document.title
  end

  def consumption_time
    estimated_minutes_to_read.seconds
  end

  private

  WORDS_PER_MINUTE = 200.0

  def estimated_minutes_to_read
    (words_in_web_document.size / WORDS_PER_MINUTE).ceil.minutes
  end

  def words_in_web_document
    @web_document_content ||= web_document.content.squish.split(' ')
  end

  def web_document
    return @web_document if @web_document.present?

    raw_content = URI.open(media_item.url).read
    @web_document = Readability::Document.new(raw_content, tags: [], remove_empty_nodes: true)
  end
end

app/models/media_item/metadata/you_tube.rb
class MediaItem::Metadata::YouTube < MediaItem::Metadata::BaseMetadata
  def title
    youtube_video[:title]
  end

  def consumption_time
    youtube_video[:duration]
  end

  private

  def youtube_video
    return @youtube_video if @youtube_video.present?

    youtube_client = YouTube::Client.new
    @youtube_video = youtube_client.video(service_id)
  end
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  before_action :set_media_items_presenter, only: %i[index show]

  def index
  end

  def show
    @media_item = current_user.media_items.includes(:notes).find(params[:id])

    respond_to do |format|
      format.turbo_stream
      format.html { render :index }
    end
  end

  def new
    @media_item = current_user.media_items.new
  end

  def create
    @media_item = current_user.media_items.build(media_item_params)

    if @media_item.save
      redirect_to media_item_path(@media_item), notice: 'Added the media.'
    else
      flash[:error] = 'There was an error adding the media.'
      render :new
    end
  end

  def edit
    @media_item = current_user.media_items.find(params[:id])
  end

  def update
    @media_item = current_user.media_items.find(params[:id])

    if @media_item.update(media_item_params)
      redirect_to media_item_path(@media_item), notice: 'Updated the media.'
    else
      flash[:error] = 'There was an error editing the media.'
      render :edit
    end
  end

  def destroy
    @media_item = current_user.media_items.find(params[:id])

    if @media_item.destroy
      redirect_to_media_list notice: "Media '#{@media_item.title_or_url}' deleted."
    end
  end

  def complete
    @media_item = current_user.media_items.find(params[:id])

    if @media_item.mark_complete
      redirect_to media_item_path(@media_item), notice: 'Marked media as completed.'
    else
      flash[:error] = 'There was an error marking the media as completed.'
      render :show
    end
  end

  def snooze
    @media_item = current_user.media_items.find(params[:id])

    snooze_until = params[:snooze_until]
    snooze_until = Time.zone.parse(snooze_until) if snooze_until.present?
    if @media_item.snooze(until_time: snooze_until)
      notice =
        if snooze_until.nil?
          'Media item was unsnoozed.'
        else
          "Snoozed until #{@media_item.snooze_until}"
        end
      redirect_to_media_list notice: notice
    else
      flash[:error] = 'There was an error snoozing the media.'
      render :show
    end
  end

  def bulk_change_queue
    queue = current_user.queues.find(params[:queue_id])
    updated_items = current_user.media_items.where(id: bulk_ids).update media_queue_id: queue.id

    flash[:notice] = "Moved #{updated_items.length} media items to '#{queue.name}'."
    redirect_ajax_to media_items_url
  end

  def bulk_mark_completed
    media_items = current_user.media_items.not_completed.where(id: bulk_ids)
    ActiveRecord::Base.transaction do
      media_items.each { |media_item| media_item.mark_complete }
    end

    flash[:notice] = "Marked #{media_items.size} media items as completed."
    redirect_ajax_to media_items_url
  end

  def bulk_destroy
    destroyed_items = current_user.media_items.where(id: bulk_ids).destroy_all

    flash[:notice] = "Deleted #{destroyed_items.size} media items."
    redirect_ajax_to media_items_url
  end

  private

  def media_item_params
    params.require(:media_item).permit(
      :url,
      :title,
      :media_queue_id,
      :media_priority_id,
      :consumption_difficulty,
      :type,
    )
  end

  def bulk_ids
    params[:ids].split(',')
  end

  def current_queue
    return unless params[:queue].present?

    @current_queue ||= current_user.queues.find(params[:queue])
  end

  def media_items_collection
    base_association = current_user
    base_association = current_queue if current_queue.present?

    base_association.media_items.includes(:queue, :priority)
  end

  def set_media_items_presenter
    @presenter =
      MediaItemsPresenter.new(
        current_user,
        media_items_collection,
        params: params,
        queue: current_queue
      )
  end
end

app/helpers/media_item_helper.rb
module MediaItemHelper
  def consumption_difficulty_classes(difficulty)
    case difficulty
    when 'easy'   then 'text-green-600'
    when 'medium' then 'text-yellow-600'
    when 'hard'   then 'text-red-600'
    else ''
    end
  end

  def toggle_class_for_type(media_item, type)
    return 'toggled' if media_item.new_record? && type == 'Article'
    return 'toggled' if media_item.type == type

    ''
  end

  def media_icon(media_item)
    case media_item.type
    when 'Article' then 'bi bi-file-text'
    when 'Video' then 'bi bi-film'
    end
  end

  def state_select_options
    [
      ['Incomplete', :not_complete],
      ['Complete', :complete],
      ['Snoozed', :snoozed],
    ]
  end

  def snooze_until_options
    now = Time.zone.today

    [
      ['Until', 'Tomorrow',   now + 1.day],
      ['Until', 'Next week',  now + 1.week],
      ['For',   'Two weeks',  now + 2.weeks],
      ['Until', 'Next month', now + 1.month],
      ['For',   'Two months', now + 2.months],
    ]
  end

  def snooze_until_menu_item(media_item, snooze_until:, prefix: nil, label:)
    snooze_url = snooze_media_item_url(media_item, snooze_until: snooze_until, queue: params[:queue])
    content_tag(:li) do
      testid = ['snooze', prefix, label].compact.map(&:downcase).join('-')
      link_to(snooze_url, class: 'menu-item', method: :post, data: { testid: testid }) do
        snooze_until_label(prefix, label) +
        content_tag(:span, class: 'text-muted ml-4') do
          if snooze_until
            "#{snooze_until.to_date} at 9 AM"
          else
            'Now'
          end
        end
      end
    end
  end

  def snooze_until_label(prefix = nil, label)
    content_tag(:span) do
      if prefix
        content_tag(:span, class: 'opacity-75 mr-1') do
          prefix
        end
      else
        ''.html_safe
      end +
      content_tag(:span, class: 'font-medium') do
        label
      end
    end
  end
end

app/views/media_items/_form.html.erb
<%= form_with model: media_item, url: form_url, scope: :media_item, data: { turbo: false } do |f| %>
  <label>Media Type</label>
  <div data-controller="toggle-buttons"
       data-toggle-buttons-field-name="media_item[type]"
       class="mb-4 toolbar">
    <span class="button toggle-button <%= toggle_class_for_type media_item, 'Article' %>"
          data-target="toggle-buttons.button"
          data-value="Article">
      Article
    </span>

    <span class="button toggle-button <%= toggle_class_for_type media_item, 'Video' %>"
          data-target="toggle-buttons.button"
          data-value="Video">
      Video
    </span>
  </div>

  <div class="row">
    <div class="column md8">
      <%= f.label :url %>
      <%= f.text_field :url, placeholder: 'https://...' %>

      <%= f.label :title, 'Title' %>
      <%= f.text_field :title, placeholder: 'Title (Optional)' %>

      <%= f.submit submit_button_text, class: 'primary button', data: { testid: 'submit-media-item' } %>
    </div>

    <div class="column md4">
      <%= f.label :media_queue_id %>
      <div class="select-wrapper">
        <%= f.select :media_queue_id,
          options_from_collection_for_select(current_user.queues, :id, :name, queue_id) %>
      </div>

      <%= f.label :media_priority_id %>

      <div class="select-wrapper">
        <%= f.select :media_priority_id,
          options_from_collection_for_select(
            current_user.media_priorities,
            :id,
            :title,
            @media_item.media_priority_id
          ) %>
      </div>

      <%= f.label :consumption_difficulty %>
      <div class="select-wrapper">
        <%= f.select :consumption_difficulty,
          select_options(
            MediaItem.consumption_difficulties,
            @media_item.consumption_difficulty,
            empty_value: 'Select a difficulty'
          ) %>
      </div>
    </div>
  </div>
<% end %>

app/views/media_items/_list_pane.html.erb
<div data-controller="bulk-actions">
  <%# Heading %>
  <div class="heading">
    <% if current_queue %>
      <h2 class="page-header pl-2" style="border-left: 3px solid <%= current_queue.color %>">
        <%= current_queue.name %>
      </h2>
    <% else %>
      <h2 class="page-header">Media</h2>
    <% end %>

    <%# Secondary actions %>
    <% if presenter.menu_items? %>
      <span data-controller="tooltip" data-tooltip-align="right">
        <button type="button" class="button icon-only" data-action="tooltip#show" data-testid="page-overflow-btn">
          <i class="bi bi-three-dots-vertical icon"></i>
        </button>
        <template data-target="tooltip.template">
          <ul class="menu">
            <% if current_queue %>
              <li><%= turbo_link_to 'Edit Queue', edit_queue_path(current_queue), class: 'menu-item' %></li>
              <li>
                <%= link_to 'Delete Queue',
                            queue_path(current_queue),
                            class: 'menu-item',
                            method: :delete,
                            data: { confirm: 'Are you sure?' } %>
              </li>
            <% end %>
            <% if current_user.pocket_integration.present? %>
              <li>
                <%= link_to 'Synchronize Pocket',
                            synchronize_integrations_path(integration_id: current_user.pocket_integration.id),
                            class: 'menu-item',
                            method: :post %>
              </li>
            <% end %>
          </ul>
        </template>
      </span>
    <% end %>
  </div>

  <%# Top-level actions %>
  <%= turbo_link_to 'Add Media',
                    new_media_item_path(queue: current_queue),
                    class: 'primary button',
                    data: { testid: 'add-media-item' } %>

  <%= render 'media_items/list_pane/filters',
              search_path: media_items_path,
              priorities: presenter.filter_priorities %>

  <% if presenter.media_items.present? %>
    <div class="relative">
      <label class="text-right">
        <%= check_box_tag :select_all_media_items,
                          'all',
                          false,
                          data: { action: 'change->bulk-actions#allItemsChanged' } %>
        Select All
      </label>

      <%# Bulk actions %>
      <div class="hidden absolute bg-white border shadow-lg rounded-md py-2 px-4 z-50"
          data-target="bulk-actions.bulkActionsToolbar"
          style="top: -170px;">

        <span class="text-lg">Bulk Actions</span>
        <div class="toolbar">
          <%= render 'media_items/list_pane/bulk_actions', queues: current_user_queues %>
        </div>
      </div>

      <%# Media items %>
      <div class="bg-white border rounded-md shadow">
        <% presenter.media_items.each do |media_item| %>
          <%= render 'media_items/list_pane/media_item',
                     media_item: media_item,
                     presenter: presenter %>
        <% end %>
      </div>

      <%= paginate presenter.media_items %>
    </div>
  <% else %>
    <%= presenter.no_media_items_message %>
  <% end %>
</div>

app/views/media_items/_media_item.html.erb
<%= turbo_frame_tag 'media-item-pane' do %>
  <div data-controller="media-viewer"
       data-media-viewer-url="<%= media_item.url %>"
       data-media-viewer-type="<%= media_item.type %>"
       data-media-viewer-media-service="<%= media_item.service_type %>"
       data-media-viewer-media-id="<%= media_item.service_id %>">

    <div class="heading">
      <div class="content">
        <h2 class="page-header mb-0 truncate">
          <span data-tippy-content="<%= media_item.url %>"><%= media_item.title_or_url %></span>
        </h1>

        <div class="toolbar text-muted mb-0">
          <div class="small media-item" data-tippy-content="Media Type">
            <i class="small <%= media_icon(media_item) %> icon"></i>
            <%= media_item.type %>
          </div>

          <div class="small media-item" data-tippy-content="Queue">
            <i class="bi bi-inbox icon"></i>
            <%= link_to media_item.queue.name, media_items_path(queue: media_item.media_queue_id), class: 'text-muted' %>
          </div>

          <% if media_item.snoozed? %>
            <div class="small media-item"
                 data-tippy-content="Snoozed until <%= media_item.formatted_snooze_until %>">
              <i class="small bi bi-clock icon"></i>
              <%= media_item.formatted_snooze_until %>
            </div>
          <% end %>

          <% if media_item.estimated_consumption_time %>
            <div class="small media-item" data-tippy-content="Estimated consumption time">
              <i class="small bi bi-watch icon"></i>
              <%= pluralize media_item.estimated_consumption_time, 'minute' %>
            </div>
          <% end %>

          <% if media_item.priority %>
            <div class="small media-item" data-tippy-content="Priority">
              <i class="small bi bi-flag icon"></i>
              <%= media_item.priority.title %>
            </div>
          <% end %>

          <% if media_item.consumption_difficulty %>
            <div class="small media-item" data-tippy-content="Consumption difficulty">
              <i class="small bi bi-sliders icon"></i>
              <span class="<%= consumption_difficulty_classes(media_item.consumption_difficulty) %>">
                <%= media_item.consumption_difficulty.capitalize %>
              </span>
            </div>
          <% end %>

          <div class="small media-item"
               data-tippy-content="<%= media_item.created_at.strftime('%F %l:%M %p') %>">
            <i class="small bi bi-calendar icon"></i>
            <%= time_ago_in_words media_item.created_at %> ago
          </div>
        </div>
      </div>

      <div class="actions">
        <span data-controller="tooltip" data-tooltip-align="right">
          <button type="button"
                  class="button icon-only"
                  data-action="tooltip#show"
                  data-testid="more-menu">
            <i class="small bi bi-three-dots-vertical icon"></i>
          </button>
          <template data-target="tooltip.template">
            <ul class="menu">
              <li>
                <%= turbo_link_to edit_media_item_path(media_item),
                                  class: 'menu-item',
                                  update_url: false do %>
                  <div class="media-item small">
                    <i class="small bi bi-pencil icon"></i>
                    Edit
                  </div>
                <% end %>
              </li>
              <li>
                <%= link_to media_item_path(media_item, queue: params[:queue]),
                            method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'menu-item' do %>
                  <div class="media-item small">
                    <i class="small bi bi-trash icon"></i>
                    Delete
                  </div>
                <% end %>
              </li>
            </ul>
          </template>
        </span>
      </div>
    </div>

    <div class="toolbar mt-4">
      <div class="button-group">
        <span data-controller="tooltip">
          <%= button_tag nil,
              type: 'button',
              class: 'button with-icon',
              data: { action: 'tooltip#show', testid: 'snooze' },
              disabled: media_item.complete? do %>

            <template data-target="tooltip.template">
              <ul class="menu">
                <% snooze_until_options.each do |prefix, label, date| %>
                  <%= snooze_until_menu_item media_item, snooze_until: date, prefix: prefix, label: label %>
                <% end %>
                <% if media_item.snoozed? %>
                  <%= snooze_until_menu_item media_item, snooze_until: nil, label: 'Unsnooze' %>
                <% end %>
              </ul>
            </template>
            <i class="bi bi-clock icon"></i>
            Snooze
          <% end %>
        </span>
        <%= button_to complete_media_item_url(media_item),
                      class: 'button with-icon',
                      method: :post,
                      data: { turbo: false },
                      disabled: media_item.complete? do %>
          <i class="bi bi-check-circle icon"></i>
          Mark Completed
        <% end %>
      </div>
      <div class="button-group">
        <%= external_link_to 'Open Media', media_item.url, class: 'button', icon_position: :left %>
        <%= button_tag nil,
                      class: 'button with-icon',
                      data: { action: 'click->media-viewer#open' } do %>
          <i class="bi bi-book icon"></i>
          Open Viewer
        <% end %>
      </div>
    </div>

    <h3 class="section-header">Notes</h3>

    <div id="notes" class="row">
      <div class="column sm12 md4 pl-0">
        <%= render 'media_notes/form', media_item: media_item %>

        <%= turbo_frame_tag 'media-item-notes' do %>
          <% if media_item.notes.any? %>
            <% media_item.notes.each do |note| %>
              <%= render 'note', note: note %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>

    <%= render 'media_viewer' %>
  </div>

  <script>
    $find('#note-title').addEventListener('keydown', function(e) {
      if (e.key !== 'Tab') return;

      e.preventDefault();
      $find('#notes .ql-editor').focus();
    })
  </script>
<% end %>

app/views/media_items/_media_viewer.html.erb
<div data-target="media-viewer.viewerWrap" class="fixed top-0 bottom-0 right-0 hidden" style="left: 45%;">
  <div class="w-full h-full bg-white">
    <div class="toolbar mb-0 justify-between py-1 px-4 border-b shadow-lg">
      <%= @media_item.url %>
      <button data-action="click->media-viewer#close" class="button icon-only">
        <i class="bi bi-x icon"></i>
      </button>
    </div>

    <div class="relative w-full h-full bg-gray-200">
      <div data-target="media-viewer.loader" class="fully-centered">
        <%= image_tag 'icons/loader', class: 'xl hoverable svg icon loader' %>
        <span class="text">Loading media...</span>
      </div>

      <div data-target="media-viewer.mediaWrap"
           class="h-full w-full fully-centered hidden"></div>
    </div>
  </div>
</div>

app/views/media_items/_note.html.erb
<%= turbo_frame_tag dom_id(note) do %>
  <div class="row mt-4">
    <div class="column sm12 md12 px-0">
      <%= render 'media_notes/note', note: note %>
    </div>
  </div>
<% end %>

app/views/media_items/edit.html.erb
<%= turbo_frame_tag 'media-item-pane' do %>
  <h1 class="page-header">Edit Media</h1>

  <%= render 'form',
             media_item: @media_item,
             submit_button_text: 'Update Media',
             queue_id: @media_item.media_queue_id,
             form_url: media_item_url(@media_item) %>
<% end %>

app/views/media_items/edit.turbo_stream.erb
<%= turbo_stream.replace 'media-item-pane' do %>
  <%= render template: 'media_items/edit.html' %>
<% end %>

app/views/media_items/index.html.erb
<div class="row h-screen"
     data-controller="detail-pane"
     data-action="turbo:before-fetch-response@document->detail-pane#displayContent"
     data-detail-pane-selected-class="border-l-2 border-l-indigo-500">
  <div class="column md4 mt-4 pr-6">
    <%= render 'media_items/list_pane', presenter: @presenter %>
  </div>

  <div class="column md8 border-l pt-8 pl-4 relative">
    <div data-target="detail-pane.loading" class="fully-centered hidden">
      <%= image_tag 'icons/loader', class: 'xl hoverable svg icon loader' %>
      <span class="text text-muted">Loading...</span>
    </div>

    <div data-target="detail-pane.content">
      <%= turbo_frame_tag 'media-item-pane' do %>
        <% if @media_item %>
          <%= render 'media_items/media_item', media_item: @media_item %>
        <% else %>
          <div class="fully-centered">
            <i class="b bi-inbox icon text-5xl text-muted"></i>
            <span class="text-lg text-muted">Select a media item</span>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/media_items/new.html.erb
<%= turbo_frame_tag 'media-item-pane' do %>
  <h2 class="page-header">Add Media</h2>

  <%= render 'form',
             media_item: @media_item,
             submit_button_text: 'Add Media',
             queue_id: params[:queue],
             form_url: media_items_url %>
<% end %>

app/views/media_items/new.turbo_stream.erb
<%= turbo_stream.replace 'media-item-pane' do %>
  <%= render template: 'media_items/new.html' %>
<% end %>

app/views/media_items/show.turbo_stream.erb
<%= turbo_stream.replace 'media-item-pane' do %>
  <%= render 'media_items/media_item', media_item: @media_item %>
<% end %>